### ISSUE TITLE
Make this driver consumable to minikube

### ISSUE THREAD

**Issue by anfernee** [machine-drivers/docker-machine-driver-vmware#1]
minikube needs to register this driver to be able to use it. There is pending on a refactor in minikube so that it's easier to add drivers: https://github.com/kubernetes/minikube/pull/2526

**Comment by frapposelli** [comment]
Assigning myself so I can ramp up on minikube.

**Comment by frapposelli** [comment]
Waiting to be merged as kubernetes/minikube#2606

Blocked by #4

**Comment by tonidy** [comment]
@frapposelli any update on this issue?

**Comment by frapposelli** [comment]
This has been merged as kubernetes/minkube#3534

**Comment by gbraad** [comment]
:+1

On Wed, Jan 23, 2019 at 12:49 AM Fabio Rapposelli
<notifications@github.com> wrote:
>
> Closed #1.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]
