### ISSUE TITLE
Make ethernet0.virtualDev configurable

### ISSUE THREAD

**Issue by MartinSGill** [machine-drivers/docker-machine-driver-vmware#14]
When trying to use this driver with boot2docker.iso it fails because the network hardware emulator doesn't appear to be supported.

![image](https://user-images.githubusercontent.com/2271740/48315252-11d80f80-e5d4-11e8-8bd7-2135bb2c9222.png)

When trying to use packer instead to create the vm for me, I discovered that it only works if I set:

"ethernet0.virtualDev": "e1000"

I'm guessing the drivers needed for vmware are not included in boot2docker, or are out-of-date for Workstation 15 so vmxnet3 doesn't work.

I'm using VMWare Workstation Pro 15, Windows, boot2docker 18.09 and docker-machine 0.14.0, build 89b8332

**Comment by MartinSGill** [comment]
Or maybe this needs to be fixed in boot2docker? https://github.com/boot2docker/boot2docker/issues/1340

**Comment by StefanScherer** [comment]
It seems it needs to be fixed in boot2docker, I've commented in https://github.com/boot2docker/boot2docker/issues/1345

**Comment by daniel-shimon** [comment]
For me removing and then adding a new NAT adapter also works for some reason..
Does folder sharing work for you? 
(Is there any /Users folder?)

**Comment by MartinSGill** [comment]
The initial cause has been resolved with changes to boot2docker cf. https://github.com/boot2docker/boot2docker/pull/1350
