### ISSUE TITLE
VM doesn't appear in Workstation 15 Library

### ISSUE THREAD

**Issue by pstroia** [machine-drivers/docker-machine-driver-vmware#22]
OS: Windows 10
Workstation: 15.1.0 build-13591040

Driver compiled from master branch with golang-1.10, minikube starts correctly and I can connect to it with a SSH client, but it would be nice if the created VMs would show up in the Workstation library.

**Comment by mikeroySoft** [comment]
If you launch minikube it when Workstation is not running, and then launch workstation, does it show up in the UI?

**Comment by evankanderson** [comment]
No. (I have the same situation.)

```
>vmrun -T ws list
Total running VMs: 2
C:\Users\evank\.minikube\machines\minikube\minikube.vmx
C:\Users\evank\Documents\Virtual Machines\Work VM\Work VM.vmx
```
<img width="107" alt="Workstation img" src="https://user-images.githubusercontent.com/7959095/75050674-4dbd7e00-5481-11ea-9ccd-4305b1cbd4a1.png">

This is after a reboot and starting Workstation after minikube is running.

**Comment by zrhoffman** [comment]
The reason the VMs don't appear in your library is that `docker-machine-driver-vmware` adds them as root. If you run

```bash
sudo '/Applications/VMware Fusion.app/Contents/MacOS/VMware Fusion'
```

then you should see them in your library.

**Comment by AZ-X** [comment]
https://github.com/AZ-X/docker-machine-driver-vmware
Thanks for attention.
