### ISSUE TITLE
No success using Bridged network with Workstation 15 Pro on Windows

### ISSUE THREAD

**Issue by kmpm** [machine-drivers/docker-machine-driver-vmware#25]
I'm trying to use docker-machine (v0.16.1) with v0.1.0 of this driver on Windows 10 - 1903 with VMware Workstation 15 Pro.
Basic machine creation and usage works as expected BUT I would really, really like to use Bridged networking and not NAT.
If I manually change the configuration of a previously created machine to use bridged network then docker-machine never finds it's IP address.
DHCP is used on the bridged network and `vmrun getGuestIPAddress` returns the assigned address so why can't this driver pick it up?

**Comment by Bl4d3666** [comment]
https://github.com/Bl4d3666/docker-machine-driver-vmware

I have update the driver it should work but i new to go. If you added `--vmware-network-type bridged` you should be good but more work still needs to be done.

**Comment by zarenner** [comment]
FYI just opened #34 to support this

**Comment by mikeroySoft** [comment]
#34 merged, should work now when building from source, we'll cut a new release soon
