### ISSUE TITLE
A reworked version

### ISSUE THREAD

**Issue by AZ-X** [machine-drivers/docker-machine-driver-vmware#27]
https://github.com/AZ-X/docker-machine-driver-vmware
Thanks for attention unless nobody visits.

**Comment by afbjorklund** [comment]
Patches ?

**Comment by AZ-X** [comment]
> Patches ?

Yes, it's a kind of patches or revision.  For instance, watch https://github.com/AZ-X/An-exhibition-of-Ed25519-signature-to-both-ssh-and-dockerd-inside-of-an-advanced-boot2docker-disc

**Comment by afbjorklund** [comment]
I don't use vmware myself, but this driver is pointed to by minikube... Maybe you would like to contribute your work to it ?

**Comment by AZ-X** [comment]
> I don't use vmware myself, but this driver is pointed to by minikube*... Maybe you would like to contribute your work to it ?
> 
> * https://minikube.sigs.k8s.io/docs/drivers/vmware/

No, I won't. One of the most important point is I do NOT use minikube. Besides, the new driver itself won't support on MacOS or any OS other than Windows.

**Comment by afbjorklund** [comment]
OK, fair enough (your choice). Maybe someone else will step up and fix the upgrade of this driver to later versions of vmware.

**Comment by AZ-X** [comment]
> OK, fair enough (your choice). Maybe someone else will step up and fix the upgrade of this driver to later versions of vmware.

My version works with latest one of VMWare. I recommend everybody to use it if on Windows, since I've used it from its born day and it never failed.

 https://github.com/AZ-X/docker-machine-driver-vmware

**Comment by mikeroySoft** [comment]
thanks for sharing :)
