### ISSUE TITLE
Compatibility with future Go versions

### ISSUE THREAD

**Issue by Bo98** [machine-drivers/docker-machine-driver-vmware#33]
Just a heads up that Go 1.17 (and the just-released 1.16 without first changing `GO111MODULE`) won't support builds that aren't in module-aware mode.

I'm not sure what the status of this project is (along with the other `docker-machine-driver-*` projects). Is there any plans to migrate to Go modules?

https://blog.golang.org/go116-module-changes

**Comment by mikeroySoft** [comment]
I've merged in the PR (#32) for supporting modules, so this should be addressed now... I haven't cut another "release" yet as I still want to pull in the other PR that's sitting there _(the Workstation team made that change in the one we ship inside Workstation itself)_, and I want to move a few other things around to tidy up the repo first, but I should have that done mid-next week.
