### ISSUE TITLE
Not able to run the driver on Intel Machine

### ISSUE THREAD

**Issue by suavebajaj** [machine-drivers/docker-machine-driver-vmware#38]
Running #`minikube start --driver vm`
getting error 

> ! 'vmware' driver reported an issue: exec: "docker-machine-driver-vmware": executable file not found in %PATH%
> * Suggestion: Install docker-machine-driver-vmware

Installed from `https://github.com/machine-drivers/docker-machine-driver-vmware/releases`
Moved into %PATH%

Now getting error  

> Exiting due to DRV_UNSUPPORTED_OS: The driver 'vm' is not supported on windows/amd64

Is there any specific drivers for Intel Machines?

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17763 N/A Build 17763

Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 12 GenuineIntel ~1910 Mhz

**Comment by dragonflylee** [comment]
you should run `minikube start --driver vmware` instead of `vm`

refer to https://minikube.sigs.k8s.io/docs/drivers/vmware/
