### ISSUE TITLE
Duplication of work

### ISSUE THREAD

**Issue by pecigonzalo** [machine-drivers/docker-machine-driver-vmware#7]
Hello, I'm the maintainer of https://github.com/pecigonzalo/docker-machine-vmwareworkstation,  its really nice to see VMWare is now creating a driver that combines VMWare workstation and VMWare Fusion.
The mentioned repo is already added in the Docker docs as a driver, I believe it would be better to merge/support the work was already done there so we can combine the efforts instead of split this even further.

**Comment by SvenDowideit** [comment]
@pecigonzalo yes please :)
The idea of this org, is to bring all the machine driver devs together into one place!

please, come join us :)

**Comment by gbraad** [comment]
This is what we would like to see happen. @anfernee, how would you see this?

**Comment by anfernee** [comment]
@pecigonzalo thanks for your great work for `docker-machine-vmwareworkstation`. It would be great to have all the support in one place. I am happy to merge any missing features from your repo. @frapposelli is also working on CI/CD pipeline too, so this becomes a long term stable support. 

Thanks again for the great work. Looking forward to your contributions to vmware driver again @pecigonzalo

**Comment by pecigonzalo** [comment]
Hey! sorry for the delays, I was on vacations that would be a good idea, I was also working on the implementation of Linux driver on mine so I think it would be beneficial for us and the community to merge them.
If you can grant me access here we can start working on combining the effort and then I can update mine to point here.

**Comment by gbraad** [comment]
Let's start with merge requests/PR as it makes the discussion for these
changes/needs more visible. Especially as we are still waiting for the CI.

**Comment by pecigonzalo** [comment]
Of course, once I have repo access or I'm added to the org, ill do this by PR.

**Comment by SvenDowideit** [comment]
@pecigonzalo sorry, I'm not sure why I didn't just add you - invite sent!!

**Comment by pecigonzalo** [comment]
To avoid more noise over here, if you want join: https://gitter.im/pecigonzalo/docker-machine-vmwareworkstation or let me know if you have a chat group.

**Comment by gbraad** [comment]
Freenode #machine-drivers
